# Generated by Django 5.2.10 on 2026-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_emailotp_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Tshirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Jacket', 'Jacket')], max_length=20),
        ),
    ]
